# Generated by Django 4.2.1 on 2023-05-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='img',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.DeleteModel(
            name='hotelImage',
        ),
    ]
